server:
  port: 8888
spring:
  application:
    name: authentication-center
  datasource:
    url: jdbc:mysql://rm-wz9794vc2ah3g166vio.mysql.rds.aliyuncs.com/authentication_center?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Ww4247794!
swagger:
  enable: true
mybatis:
  mapperLocations: classpath:mapper/*.xml

